# Welcome {.unnumbered}

This book contains all of the code used to gather the data that can be found in the [Data Warehouse](https://localfoodeconomics.com/data/access-the-data/) and the [Food and Agriculture Mapper and Explorer](https://localfoodeconomics.com/data/food-and-agriculture-data-explorer/).

The Data and Metrics initiative is focused on fostering greater data efficacy and literacy across local and regional food systems by engaging project stakeholders in completing a gap analysis of existing local and regional food system data, fostering peer mentorship, and providing technical assistance. In part to accomplish these goals, teams of researchers and community partners reviewed and compiled available data using an equity lens into a single data warehouse to facilitate analysis and visualization.

The initiative first began by reviewing the mission statements from national local and regional food system network leaders. Mission statements were organized into six categories -- labor, farm development/local food sales, business development/food infrastructure, community wealth/well-being, nutrition security/food access, and policy. For each of the categories, except for policy, the teams created document briefs identifying key related data indicators available nationwide at the county level. Creators of data warehouses, data explorers, and data dashboards encounter several challenges when it comes to the issue of equity. Reliance on existing data limited the ability to disaggregate data by dimensions of race, ethnicity, and citizenship status. As a result, we encourage the use of practices that invite community members to help contextualize data, share their personal stories, and amplify community solutions. The data warehouse is open-source and additional contributions are welcome.

The goals of the project are to:

-   support the utilization of data in program evaluation and decision making; and

-   improve access to data from an array of sources including government, NGOs, network partners, and researchers.

# License

This website is free to use and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/)
